class Rep {
  List<Map<String, dynamic>> get jsonData => [
        {
          'age': 20,
          'fingers': 2.0,
          'name': 'Andrew',
          'nicknames': [
            'Saymon',
            'Nindja55',
            'Claren',
            'Chen',
          ],
        },
        {
          'age': 21,
          'fingers': 2.6,
          'name': "Ma'lik",
          'nicknames': [
            'Alison',
            'Faruk',
            'Gonzales',
            'Graymond',
            'Serb',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Rayan',
          'nicknames': [
            'Vovan',
            'Dr.Papper666',
            'Ludwig11',
            'Hans0n',
            'Chedw1g',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Max',
          'nicknames': [
            'Leron_Baron',
            'Lapuk',
            'Cr@ven',
            'Salex',
            'Gratew00d',
            'Hastoor',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Alex',
          'nicknames': [
            'Si-dzyan-pin',
            'Caer',
            'Morhen',
            'Valoris',
            'Sebirian',
            'Nadjel',
            'Kleo',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Ivan',
          'nicknames': [
            'Gordon',
            'Ramzy',
            'Looser999',
            'Fahrid-12',
            'Appolon-11',
            'Dzerjinskiy',
            'Clapton',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Kate',
          'nicknames': [
            'USA_Soldier',
            'Jahakta',
            'Lambersy',
            'Sylorisity',
            'Hagrem',
            'Valista',
            'Corbien',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Julia',
          'nicknames': [
            'Orsa',
            'Enigma',
            'Jul',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Jane',
          'nicknames': [
            'Fibby',
            'Galya_otmena',
            'Stroby',
            "In'-Lan'",
            'Kaidzu',
            'Tesseraque',
            'Kurisity',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Jacob',
          'nicknames': [
            'Callen',
            'Fellaris_',
            'Jimmy',
            'Queen',
            'Old-Boy09',
            'Haxwell',
            'Daymond',
            'Leardy',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Jax',
          'nicknames': [
            'Jinada',
            'Frostmorne',
            'Darwin',
            'DeepLink-75',
            'Oraxa',
            'Lion',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Ajax',
          'nicknames': [
            'Qster',
            'Afterbrith',
            'Zip-token',
            'Clorsen',
            'Dreadnought-19',
            'Astranomad',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Freddy',
          'nicknames': [
            'Boogga-boss',
            'Trenda_lore',
            "Gazmyas'ochka",
            'Leolis',
            'Le-les',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Henry',
          'nicknames': [
            'Col2d6',
            'Sorabi',
            'Ichi-one',
            'Polonez',
            'Tolstiy_chan',
            'Varenok',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Caleb',
          'nicknames': [
            'Di-psy',
            'Craken',
            'Glenmore',
            'Raven',
            'Polax',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Evgen',
          'nicknames': [
            'Erjan',
            'Garus',
            'Wahit',
            'Utigatana',
            'Lightwood',
            'xeon',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Danila Ishutin',
          'nicknames': [
            'Dandy',
            'Rudge',
            'Pudge',
            'Toxc_Midlaner',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Greg',
          'nicknames': [
            'Nightfall',
            'Wats0n',
            'Mid0ne',
            'Sumail',
            'Nikobebra',
          ],
        },
        {
          'age': 25,
          'fingers': 9.5,
          'name': 'Lexx',
          'nicknames': [
            'Rumpelshtintsen',
            'Kwebbeck',
            'Sarma',
            'Klondyke',
          ],
        },
      ];
}
